spring:
  application:
    name: spring-cloud-eureka-auth
server:
  port: 8772
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
 